services:
  - type: web
    name: qr-attendance-api
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app.main:app -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: postgresql://postgress:Db70pCsQp7kDPOCS8ss4fBZeWl0qbeDC@dpg-d00dlu7gi27c73b6838g-a/attendance_db_zuoo

databases:
  - name: attendance_db
    databaseName: attendance_db_zuoo
    plan: free





